# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# From gfplot .travis.yml:

warnings_are_errors: false

r_packages:
  - devtools
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
